# Generated by Django 3.0.10 on 2020-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
